### ISSUE TITLE
Build error on OSX

### ISSUE THREAD

**Issue by leinonen** [Geocent/node-hmd#1]
I am unable to build this thing.
I am using OSX Yosemite 10.10.2, NodeJS 0.12.5 and have XCode installed.
Btw, I want to use it for the DK2.

In file included from ../src/platform/mac/LibOVR/Src/Util/../../Include/OVR_Kernel.h:35:
../src/platform/mac/LibOVR/Include/../Src/Kernel/OVR_Nullptr.h:90:16: error: 
      reference to 'nullptr_t' is ambiguous
        inline nullptr_t nullptr_get()
               ^
../src/platform/mac/LibOVR/Include/../Src/Kernel/OVR_Nullptr.h:66:15: note: 
      candidate found by name lookup is 'std::nullptr_t'
        class nullptr_t
              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstddef:58:30: note: 
      candidate found by name lookup is 'std::__1::nullptr_t'
struct _LIBCPP_TYPE_VIS_ONLY nullptr_t
                             ^
In file included from ../src/platform/mac/LibOVR/Src/Util/Util_ImageWindow.cpp:26:
In file included from ../src/platform/mac/LibOVR/Src/Util/../../Include/OVR_Kernel.h:35:
../src/platform/mac/LibOVR/Include/../Src/Kernel/OVR_Nullptr.h:92:13: error: 
      reference to 'nullptr_t' is ambiguous
            nullptr_t n = { };
            ^
../src/platform/mac/LibOVR/Include/../Src/Kernel/OVR_Nullptr.h:66:15: note: 
      candidate found by name lookup is 'std::nullptr_t'
        class nullptr_t
              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstddef:58:30: note: 
      candidate found by name lookup is 'std::__1::nullptr_t'
struct _LIBCPP_TYPE_VIS_ONLY nullptr_t
                             ^
In file included from ../src/platform/mac/LibOVR/Src/Util/Util_ImageWindow.cpp:26:
In file included from ../src/platform/mac/LibOVR/Src/Util/../../Include/OVR_Kernel.h:35:
../src/platform/mac/LibOVR/Include/../Src/Kernel/OVR_Nullptr.h:93:20: error: 
      use of undeclared identifier 'n'
            return n;
                   ^
.....
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/hmd/src/platform/mac/LibOVR/Src/Util/Util_ImageWindow.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)

**Comment by GeoJosh** [comment]
Thanks for the report. For completeness sake, what is your currently installed version of the Oculus runtime?
--
Joshua Penton

e: joshua.penton@geocent.com<mailto:joshua.penton@geocent.com>
o: 228.688.3392
f: 228.688.6531

On Jun 29, 2015, at 3:33 PM, Peter Leinonen <notifications@github.com<mailto:notifications@github.com>> wrote:


I am unable to build this thing.
I am using OSX Yosemite 10.10.2, NodeJS 0.12.5 and have XCode installed.

In file included from ../src/platform/mac/LibOVR/Src/Util/../../Include/OVR_Kernel.h:35:
../src/platform/mac/LibOVR/Include/../Src/Kernel/OVR_Nullptr.h:90:16: error:
reference to 'nullptr_t' is ambiguous
inline nullptr_t nullptr_get()
^
../src/platform/mac/LibOVR/Include/../Src/Kernel/OVR_Nullptr.h:66:15: note:
candidate found by name lookup is 'std::nullptr_t'
class nullptr_t
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstddef:58:30: note:
candidate found by name lookup is 'std::__1::nullptr_t'
struct _LIBCPP_TYPE_VIS_ONLY nullptr_t
^
In file included from ../src/platform/mac/LibOVR/Src/Util/Util_ImageWindow.cpp:26:
In file included from ../src/platform/mac/LibOVR/Src/Util/../../Include/OVR_Kernel.h:35:
../src/platform/mac/LibOVR/Include/../Src/Kernel/OVR_Nullptr.h:92:13: error:
reference to 'nullptr_t' is ambiguous
nullptr_t n = { };
^
../src/platform/mac/LibOVR/Include/../Src/Kernel/OVR_Nullptr.h:66:15: note:
candidate found by name lookup is 'std::nullptr_t'
class nullptr_t
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstddef:58:30: note:
candidate found by name lookup is 'std::__1::nullptr_t'
struct _LIBCPP_TYPE_VIS_ONLY nullptr_t
^
In file included from ../src/platform/mac/LibOVR/Src/Util/Util_ImageWindow.cpp:26:
In file included from ../src/platform/mac/LibOVR/Src/Util/../../Include/OVR_Kernel.h:35:
../src/platform/mac/LibOVR/Include/../Src/Kernel/OVR_Nullptr.h:93:20: error:
use of undeclared identifier 'n'
return n;
^
.....
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/hmd/src/platform/mac/LibOVR/Src/Util/Util_ImageWindow.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)

**Comment by leinonen** [comment]
I have version 0.5.0.1 of the Oculus Runtime installed.

**Comment by GeoJosh** [comment]
Thanks for the information. Just to verify for completeness, when version of XCode and XCode command line tools do you have installed?

Sent from mobile device.

On Jun 30, 2015, at 00:45, Peter Leinonen <notifications@github.com<mailto:notifications@github.com>> wrote:


I have version 0.5.0.1 of the Oculus Runtime installed.

-

**Comment by leinonen** [comment]
XCode Version 6.3.1 (6D1002), and I guess the command line tools is the same?

**Comment by leinonen** [comment]
There is an update for XCode to 6.4. Maybe I should try that?

**Comment by putrinolab1** [comment]
Hi there @leinonen. We have had a possibly issue as you while on a Yosemite 10.10, running XCode 6.4. We are encountering several warnings followed by errors beginning with:

`In file included from ../src/platform/mac/LibOVR/Src/Util/../../Include/OVR_Kernel.h:35:
../src/platform/mac/LibOVR/Include/../Src/Kernel/OVR_Nullptr.h:90:16: error: 
      reference to 'nullptr_t' is ambiguous
        inline nullptr_t nullptr_get()
`

and concluding with: 

`fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.`

Any updates on this?

**Comment by GeoJosh** [comment]
I've looked into this and it appears to be an issue with the updated LLVM version of the C++ standard library containing an incomplete or erroneous definition for std::nullptr_t. I've updated the bindings for building on OSX to use the GCC C++ standard library and this appears to resolve the issue. Let me know if this fixes the issue for you.
